# Generated by Django 2.2 on 2020-05-19 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200519_0419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Врачи'},
        ),
        migrations.AlterModelOptions(
            name='exceptionword',
            options={'verbose_name': 'Слова-исключения'},
        ),
        migrations.AlterModelOptions(
            name='fword',
            options={'verbose_name': 'Ругательства'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['title'], 'verbose_name': 'Специальности'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='created',
        ),
        migrations.AddField(
            model_name='review',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='exceptionword',
            name='word',
            field=models.CharField(max_length=150, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='fword',
            name='word',
            field=models.CharField(max_length=150, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='review',
            name='formatted_text',
            field=models.TextField(verbose_name='Форматированный текст'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(default='', verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Специальность'),
        ),
    ]
