# Generated by Django 2.2 on 2020-05-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200519_0609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Врача', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterModelOptions(
            name='exceptionword',
            options={'verbose_name': 'Слово-исключение', 'verbose_name_plural': 'Слова-исключения'},
        ),
        migrations.AlterModelOptions(
            name='fword',
            options={'verbose_name': 'Ругательство', 'verbose_name_plural': 'Ругательства'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['title'], 'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.AddField(
            model_name='review',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1'),
            preserve_default=False,
        ),
    ]
