# Generated by Django 2.2 on 2020-05-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20200519_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
